export interface Member {
  name: string;
  school?: string;
  graduationYear: number | null;
}

// Public roster only. Private survey fields such as emails, parent contacts,
// phone numbers, signatures, Discord tags, and waiver responses are excluded.
export const members: Member[] = [
  { name: "Grace Ling", school: "Northview High School", graduationYear: 2024 },
  { name: "Qiushi (Rachel) Li", school: "Parkview High School", graduationYear: 2024 },
  { name: "Annie Lin", school: "North Atlanta High School", graduationYear: 2024 },
  { name: "Karen Yan", school: "Lambert High School", graduationYear: 2024 },
  { name: "Evelyn Jin", school: "Northview High School", graduationYear: 2024 },
  { name: "Jason Zhang", school: "Lambert High School", graduationYear: 2024 },
  { name: "Carol Li", school: "Chamblee High School", graduationYear: 2024 },
  { name: "Tyler Zheng", school: "Brookwood High School", graduationYear: 2024 },
  { name: "Claire Jing", school: "Northview High School", graduationYear: 2025 },
  { name: "Michelle Hu", school: "Johns Creek High School", graduationYear: 2025 },
  { name: "Emily Song", school: "Innovation Academy", graduationYear: 2025 },
  { name: "Mathew Jiang", school: "Johns Creek High School", graduationYear: 2025 },
  { name: "Jiaying Li", school: "Brookwood High School", graduationYear: 2025 },
  { name: "Clara Yuan", school: "Ocee Elementary", graduationYear: 2025 },
  { name: "Jayden Wang", school: "Chattahoochee High School", graduationYear: 2025 },
  { name: "William Xu", school: "Johns Creek High School", graduationYear: 2025 },
  { name: "Daniel Zheng", graduationYear: 2025 },
  { name: "Samuel Zheng", school: "Brookwood High School", graduationYear: 2025 },
  { name: "Jayden Liu", school: "Lambert High School", graduationYear: 2026 },
  { name: "Herui (Ray) Li", school: "South Forsyth High", graduationYear: 2026 },
  { name: "Kunyuan (Eric) Zou", school: "Lambert High School", graduationYear: 2026 },
  { name: "Angela Zhou", school: "Johns Creek High School", graduationYear: 2026 },
  { name: "Ryan Tran", school: "Lambert High", graduationYear: 2026 },
  { name: "Edwin Tang", school: "Northview", graduationYear: 2026 },
  { name: "Julia Ding", school: "Walton High School", graduationYear: 2026 },
  { name: "Dario Liu", graduationYear: 2026 },
  { name: "Eric Tang", school: "Denmark High School", graduationYear: 2026 },
  { name: "Zhexin Hua", school: "Lambert High School", graduationYear: 2026 },
  { name: "Miya Ji", school: "Alpharetta High School", graduationYear: 2026 },
  { name: "Erica Ng", school: "Northview High School", graduationYear: 2026 },
  { name: "Lan Yu Xu", school: "Johns Creek High School", graduationYear: 2026 },
  { name: "Eric Zhang", school: "Lambert High School", graduationYear: 2026 },
  { name: "Bruce Huang", school: "North Gwinnett High School", graduationYear: 2026 },
  { name: "Hanjiang Dai", school: "Lambert High School", graduationYear: 2026 },
  { name: "Xirui Li", school: "Lambert High School", graduationYear: 2026 },
  { name: "Rebecca Yin", school: "Woodward Academy", graduationYear: 2026 },
  { name: "Brooke Deng", school: "Wheeler High School", graduationYear: 2026 },
  { name: "Sarah Wang", school: "Acton Boxborough Regional High School", graduationYear: 2026 },
  { name: "Alex Fang", school: "Innovation Academy", graduationYear: 2026 },
  { name: "Sofia Wu", school: "Woodward Academy", graduationYear: 2026 },
  { name: "Carter Guo", school: "Chattahoochee High School", graduationYear: 2026 },
  { name: "Haoyi Qin", school: "Decatur High School", graduationYear: 2026 },
  { name: "Haotong Li", school: "Mill Creek High School", graduationYear: 2026 },
  { name: "Zhaoqi Li", school: "Northview High School", graduationYear: 2026 },
  { name: "Lilin Zhao", school: "Northview High School", graduationYear: 2026 },
  { name: "Jason Whitney", school: "Milton HS", graduationYear: 2026 },
  { name: "Amber Zhang", school: "Lambert High School", graduationYear: 2026 },
  { name: "April Chen", school: "North Gwinnett Middle", graduationYear: 2027 },
  { name: "Hannah Gao", school: "Walton High School", graduationYear: 2027 },
  { name: "Mason Cao", school: "Lambert High", graduationYear: 2027 },
  { name: "Mike Chai", school: "Riverwatch Middle School", graduationYear: 2027 },
  { name: "Kevin Fan", school: "Johns Creek High School", graduationYear: 2027 },
  { name: "Claire Ling", school: "Northview High School", graduationYear: 2027 },
  { name: "Hope Liu", school: "Northview High School", graduationYear: 2027 },
  { name: "Cheng Jason", school: "Northwestern Middle School", graduationYear: 2027 },
  { name: "Fia Wang", school: "Northview High School", graduationYear: 2027 },
  { name: "Mingxuan (Mia) Zhou", school: "South Forsyth Middle School", graduationYear: 2027 },
  { name: "Sophia Jiang", school: "Decatur High School", graduationYear: 2027 },
  { name: "James Zhang", school: "Lambert High School", graduationYear: 2027 },
  { name: "Zizhan Wang", school: "River Trail Middle School", graduationYear: 2027 },
  { name: "Dennis Xu", school: "Johns Creek High School", graduationYear: 2027 },
  { name: "Jiaxuan Cao", school: "Lambert High School", graduationYear: 2027 },
  { name: "Brady Zhou", school: "Walton High School", graduationYear: 2027 },
  { name: "Aaron Chen", school: "Walton High", graduationYear: 2027 },
  { name: "Nathan Deng", school: "Wheeler High School", graduationYear: 2027 },
  { name: "Thomas Bai", school: "River Trail Middle School", graduationYear: 2027 },
  { name: "Jessica He", school: "Walton High School", graduationYear: 2027 },
  { name: "Minh Nguyen", school: "Walton High School", graduationYear: 2027 },
  { name: "Zitong Yun", school: "Johns Creek High School", graduationYear: 2027 },
  { name: "Shicheng Wei", school: "South Forsyth High School", graduationYear: 2027 },
  { name: "James Cheng", school: "Milton High", graduationYear: 2027 },
  { name: "Andrew Lao", school: "Chattahoochee High School", graduationYear: 2027 },
  { name: "Yixiao (Ethan) Dong", school: "Walton High", graduationYear: 2027 },
  { name: "Katie Chen", school: "Walton High School", graduationYear: 2027 },
  { name: "Julie Chen", school: "Walton High School", graduationYear: 2027 },
  { name: "Justin Zheng", school: "Brookwood High School", graduationYear: 2027 },
  { name: "April Chen", school: "North Gwinnett High School", graduationYear: 2027 },
  { name: "Daniel Yang", school: "Walton High School", graduationYear: 2027 },
  { name: "Andrew Kuang", graduationYear: 2027 },
  { name: "Larry Wang", school: "North Gwinnett High School", graduationYear: 2027 },
  { name: "Xinle Tong", school: "Parkview High School", graduationYear: 2027 },
  { name: "Evan Tran", school: "Riverwatch Middle", graduationYear: 2028 },
  { name: "Melody Jin", school: "River Trail Middle School", graduationYear: 2028 },
  { name: "Sophie Zhou", school: "Autrey Mill Middle School", graduationYear: 2028 },
  { name: "Andrew Jiang", school: "Autrey Mill Middle School", graduationYear: 2028 },
  { name: "Jeremy Wu", school: "Autrey Mill Middle School", graduationYear: 2028 },
  { name: "Scarlett Chen", school: "Webb Bridge Middle School", graduationYear: 2028 },
  { name: "Olivia Ma", school: "River Trail Middle School", graduationYear: 2028 },
  { name: "Andrew Pan", school: "Five Forks Middle School", graduationYear: 2028 },
  { name: "Janelle Yuan", school: "Webb Bridge Middle School", graduationYear: 2028 },
  { name: "Vincent Ng", school: "River Trail Middle School", graduationYear: 2028 },
  { name: "Ellean Chen", school: "Chamblee Middle School", graduationYear: 2028 },
  { name: "Shuran Gu", school: "River Trail Middle School", graduationYear: 2028 },
  { name: "Eden Yun Yu", school: "Autrey Mill Middle School", graduationYear: 2028 },
  { name: "Joshua Peng", school: "Desana Middle School", graduationYear: 2028 },
  { name: "Joanna Yang", school: "Homeschool", graduationYear: 2028 },
  { name: "Andy Zhu", school: "Tricum Middle School", graduationYear: 2028 },
  { name: "George Zhang", school: "River Trail Middle School", graduationYear: 2029 },
  { name: "Dan Miao", school: "Riverwatch Middle School", graduationYear: 2028 },
  { name: "Richard Li", school: "Northview High School", graduationYear: 2028 },
  { name: "Betty Wu", school: "Innovation Academy", graduationYear: 2028 },
  { name: "Cindy Wu", school: "Innovation Academy", graduationYear: 2028 },
  { name: "Andrew Wu", school: "Innovation Academy", graduationYear: 2028 },
  { name: "Justin An", school: "Northview High School", graduationYear: 2028 },
  { name: "Zihan Zhao", school: "Alpharetta High School", graduationYear: 2028 },
  { name: "Kyle Lin", school: "Walton High School", graduationYear: 2028 },
  { name: "Devin Yang", school: "Walton High School", graduationYear: 2028 },
  { name: "Andrew Wang", school: "Paideia School", graduationYear: 2028 },
  { name: "Mitchell Kuang", school: "Duluth High School", graduationYear: 2027 },
  { name: "Jason Cheng", school: "Milton High School", graduationYear: 2028 },
  { name: "Samuel Han", school: "Lambert High School", graduationYear: 2028 },
  { name: "Yanzi Chen", school: "Northview High School", graduationYear: 2028 },
  { name: "Olivia Chen", school: "Northview High School", graduationYear: 2028 },
  { name: "Sasha Morgan", school: "Johns Creek High School", graduationYear: 2028 },
  { name: "Jordan Chen", school: "Northview High School", graduationYear: 2028 },
  { name: "Yishen Miao", school: "Northview High School", graduationYear: 2028 },
  { name: "Bella Zhang", school: "Beacon Hill Middle School", graduationYear: 2029 },
  { name: "Chloe Lin", school: "Westminster", graduationYear: 2029 },
  { name: "Eli Brown", school: "Dolvin Elementary", graduationYear: 2029 },
  { name: "Alexander Zai", school: "Fulton Science Academy", graduationYear: 2029 },
  { name: "Anna Jia", school: "Westminster", graduationYear: 2029 },
  { name: "Gavin Zhang", school: "Five Forks Middle School", graduationYear: 2029 },
  { name: "Justin Xu", school: "North Gwinnett Middle School", graduationYear: 2029 },
  { name: "Olivia Sung", school: "River Trail Middle School", graduationYear: 2029 },
  { name: "Fibe Wang", school: "River Trail Middle School", graduationYear: 2029 },
  { name: "Phoebe Hu", school: "South Forsyth Middle School", graduationYear: 2029 },
  { name: "Sophie Lin", school: "Autrey Mill Middle School", graduationYear: 2029 },
  { name: "Emma Chen", school: "Webb Bridge Middle School", graduationYear: 2029 },
  { name: "Emma Fu", school: "AMMS", graduationYear: 2029 },
  { name: "Jacey Wu", school: "The Westminster Schools", graduationYear: 2029 },
  { name: "Hanrui Huang", school: "Autrey Mill Middle School", graduationYear: 2029 },
  { name: "Mia Jiang", school: "Fulton Science Academy", graduationYear: 2029 },
  { name: "Nick Xu", school: "The Paideia School", graduationYear: 2029 },
  { name: "Zhengyi Dai", school: "Autrey Mill Middle School", graduationYear: 2029 },
  { name: "Yixuan Shi", school: "Hopewell Middle School", graduationYear: 2029 },
  { name: "Eric Lin", school: "Lambert High School", graduationYear: 2029 },
  { name: "Evie Li", school: "Sugar Hill Christian Academy", graduationYear: 2029 },
  { name: "Kaiwen Liu", school: "Johns Creek High School", graduationYear: 2029 },
  { name: "Anna Wang", school: "Sope Creek", graduationYear: 2030 },
  { name: "Jason Li", school: "Lake Windward Elementary School", graduationYear: 2030 },
  { name: "Elizabeth Xu", school: "North Gwinnett Middle School", graduationYear: 2030 },
  { name: "Luffy Lin", school: "Glenn C. Jones Middle School", graduationYear: 2030 },
  { name: "William Wang", school: "North Gwinnett Middle School", graduationYear: 2030 },
  { name: "Alissa Cheng", school: "Crabapple Crossing Elementary", graduationYear: 2030 },
  { name: "Sophia Zhao", school: "Riverwatch Middle School", graduationYear: 2030 },
  { name: "Joy Yang", school: "Webb Bridge Middle School", graduationYear: 2030 },
  { name: "Vina Zhang", school: "South Forsyth Middle School", graduationYear: 2030 },
  { name: "Chloe Cheng", school: "Taylor Road Middle School", graduationYear: 2030 },
  { name: "Rachel Tan", school: "International Charter Academy of Georgia", graduationYear: 2030 },
  { name: "Yu Luan", school: "Autrey Mill Middle School", graduationYear: 2030 },
  { name: "Melissa Qiu", school: "FSA", graduationYear: 2030 },
  { name: "Sarah Li", school: "Piney Grove Middle School", graduationYear: 2030 },
  { name: "Haoxin Cao", school: "Crews Middle School", graduationYear: 2030 },
  { name: "Joseph Dong", school: "The Walker School", graduationYear: 2030 },
  { name: "Renye Zhao", school: "Head Elementary", graduationYear: 2031 },
  { name: "Xinye Zhao", school: "Head Elementary", graduationYear: 2031 },
  { name: "Shiou (Esther) Li", school: "Brookwood Elementary School", graduationYear: 2031 },
  { name: "Cindy Zhao", school: "State Bridge Crossing Elementary", graduationYear: 2031 },
  { name: "Hanya Yang", school: "Brookwood Elementary School", graduationYear: 2031 },
  { name: "Justin Zhang", school: "State Bridge Crossing Elementary", graduationYear: 2031 },
  { name: "Alex Sun", school: "Shiloh Point Elementary School", graduationYear: 2031 },
  { name: "Jeremy Ma", school: "Ocee Elementary", graduationYear: 2031 },
  { name: "Elina Ma", school: "Wilson Creek Elementary School", graduationYear: 2031 },
  { name: "Eric Wu", school: "Settles Bridge Elementary School", graduationYear: 2031 },
  { name: "Jason Ling", school: "Shakerag Elementary", graduationYear: 2031 },
  { name: "Jessica Fu", school: "MBES", graduationYear: 2031 },
  { name: "Blair Zhu", school: "Autrey Mill Middle School", graduationYear: 2031 },
  { name: "Jasper Wu", school: "Mount Bethel Elementary School", graduationYear: 2031 },
  { name: "Kylie Wang", school: "Chattahoochee Elementary", graduationYear: 2031 },
  { name: "Brad Huang", school: "North Gwinnett Middle School", graduationYear: 2031 },
  { name: "Aaron Liu", school: "Westminster", graduationYear: 2031 },
  { name: "Jennifer Liu", school: "Autrey Mill Middle School", graduationYear: 2031 },
  { name: "Haotian Cao", school: "Crews Middle School", graduationYear: 2032 },
  { name: "Milo Shih", school: "Dolvin", graduationYear: 2032 },
  { name: "Shana Ji", school: "Barnwell Elementary", graduationYear: 2032 },
  { name: "Yuexuan Li", school: "State Bridge Crossing Elementary", graduationYear: 2032 },
  { name: "Alissa Cheng", school: "Crabapple Elementary School", graduationYear: 2032 },
  { name: "Abby Cai", school: "Shakerag Elementary", graduationYear: 2032 },
  { name: "Bella Jing", school: "Findley Oaks Elementary", graduationYear: 2032 },
  { name: "Anna Jing", school: "Findley Oaks Elementary", graduationYear: 2032 },
  { name: "Kellyn Fan", school: "Barnwell Elementary", graduationYear: 2032 },
  { name: "Harry Liu", school: "Shakerag Elementary", graduationYear: 2032 },
  { name: "Ally Yang", school: "Findley Oaks Elementary", graduationYear: 2032 },
  { name: "Jolin Zhang", school: "Medlock Bridge Elementary School", graduationYear: 2032 },
  { name: "Michael Foley", school: "Settles Bridge Elementary", graduationYear: 2032 },
  { name: "Florence Hu", school: "Mount Bethel Elementary School", graduationYear: 2032 },
  { name: "Sarah Li", school: "Piney Grove Middle School", graduationYear: 2032 },
  { name: "Amber Hu", school: "Roberts Elementary School", graduationYear: 2032 },
  { name: "Ella Jing", school: "Roberts Elementary School", graduationYear: 2032 },
  { name: "Audrey Wang", school: "Johns Creek Elementary", graduationYear: 2032 },
  { name: "Evan Cai", school: "Piney Grove Middle School", graduationYear: 2031 },
  { name: "Katelyn Quan", school: "Ivy Creek Elementary", graduationYear: 2032 },
  { name: "Natalie Zhang", school: "Webb Bridge Middle School", graduationYear: 2032 },
  { name: "Cecilia Bao", school: "Fulton Science Academy", graduationYear: 2032 },
  { name: "Lucas Li", school: "Fulton Science Academy", graduationYear: 2032 },
  { name: "Daisy Liu", school: "Autrey Mill MS", graduationYear: 2032 },
  { name: "Henry Gou", school: "Webb Bridge Middle", graduationYear: 2032 },
  { name: "Matthew Liu", school: "Woodward North", graduationYear: 2033 },
  { name: "Lucy Lin", school: "Jackson Elementary", graduationYear: 2033 },
  { name: "Corey Chen", school: "Suwanee Elementary School", graduationYear: 2033 },
  { name: "Lucas Zhang", school: "Sharon Elementary School", graduationYear: 2033 },
  { name: "Anyi Wang", school: "Shakerag Elementary", graduationYear: 2033 },
  { name: "Lydia Jiang", graduationYear: 2033 },
  { name: "Abigail Cai", school: "Shakerag Elementary", graduationYear: 2033 },
  { name: "Anna Hu", school: "Dolvin Elementary School", graduationYear: 2034 },
  { name: "Hanrui Yang", school: "Brookwood Elementary School", graduationYear: 2034 },
  { name: "Vivian Cai", school: "Shakerag Elementary", graduationYear: 2034 },
  { name: "Claire Yang", school: "Findley Oaks Elementary", graduationYear: 2034 },
  { name: "Corey Chen", school: "Suwanee Elementary School", graduationYear: 2034 },
  { name: "Audrey Wang", school: "Fulton Science Academy", graduationYear: 2036 },
  { name: "Nina Wang", school: "Walnut Grove Elementary School", graduationYear: 2035 },
  { name: "Dylan Ashford", school: "Settles Bridge Elementary", graduationYear: 2034 },
  { name: "Dylan Liu", school: "Suwanee Elementary School", graduationYear: 2034 },
  { name: "Chloe Chen", school: "Ivy Creek Elementary School", graduationYear: 2034 },
  { name: "Benjamin Lu", school: "Sharon Elementary School", graduationYear: 2034 },
  { name: "Jillian He", school: "Barnwell Elementary", graduationYear: 2035 },
  { name: "Ziqian Li", school: "State Bridge Crossing Elementary", graduationYear: 2035 },
  { name: "Mason Wang", school: "Sharon Elementary School", graduationYear: 2035 },
  { name: "Jinrun Xie", school: "Abbotts Hill Elementary School", graduationYear: 2035 },
  { name: "Vivian Cai", school: "Shakerag Elementary", graduationYear: 2035 },
  { name: "Jeffrey Lu", school: "Sharon Elementary School", graduationYear: 2036 },
  { name: "Harper Liu", school: "Suwanee Elementary School", graduationYear: 2036 },
  { name: "Allison Wang", school: "Woodward North", graduationYear: 2037 },
  { name: "Elizabeth Lin", school: "Riverside Elementary", graduationYear: 2037 },
  { name: "Leo Wang", school: "Fulton Science Academy", graduationYear: null },
  { name: "Miles Wang", school: "Findley Oaks", graduationYear: null },
  { name: "Maggie Ma", school: "Findley Oak Elementary", graduationYear: null },
  { name: "Sunny Chen", school: "Johns Creek Elementary", graduationYear: null },
  { name: "Yumeng (Amy) Jiang", school: "Autrey Mill Middle School", graduationYear: null },
  { name: "Angel Yang", school: "Findley Oaks Elementary School", graduationYear: null },
  { name: "Brian Ma", school: "Chattahoochee High", graduationYear: null },
  { name: "Aiden Xue", school: "Ocee Elementary School", graduationYear: null },
  { name: "Mia Xue", school: "Preston Montessori School", graduationYear: null },
  { name: "Dara Du", school: "East Side Elementary School", graduationYear: null },
  { name: "Hongju Lin", school: "Alcova Elementary School", graduationYear: null },
  { name: "Jonathon Wu", school: "River Trail Middle School", graduationYear: null },
  { name: "Jamie Zhou", school: "River Trail Middle School", graduationYear: null },
  { name: "Hannah Chu", school: "Fulton Science Academy", graduationYear: null },
  { name: "Raymond Li", school: "Settles Bridge Elementary School", graduationYear: null },
  { name: "Ethan Dong", school: "Brookwood Elementary School", graduationYear: null },
  { name: "Isaac Dong", school: "Brookwood Elementary School", graduationYear: null },
  { name: "Jason Huang", school: "Woodward Academy", graduationYear: null },
  { name: "Ziyi Huang", school: "Woodward Academy", graduationYear: null },
  { name: "Meilin Lu", school: "Parsons Elementary School", graduationYear: null },
  { name: "Allen Lu", school: "Kids R Kids Duluth", graduationYear: null },
  { name: "Jessie Zhao", school: "Creekland Middle School", graduationYear: null },
  { name: "Kevin Lin", school: "Riverwatch Middle School", graduationYear: null },
  { name: "Britany Song", school: "Autrey Mill Middle School", graduationYear: null },
  { name: "Sophia Yuan", school: "Parkview High School", graduationYear: null },
  { name: "Elaine Zhang", school: "Fulton Science Academy", graduationYear: null },
  { name: "Audrey Vongkamheng", school: "Home Schooling", graduationYear: null },
  { name: "Nathan Vongkamheng", school: "Home Schooling", graduationYear: null },
  { name: "Alex Jr Huang", school: "Chattahoochee Elementary School", graduationYear: null },
  { name: "Lucas Stevens", school: "Lake Windward Elementary School", graduationYear: null },
];
